### PR TITLE
Push a single DNS server over DHCP

### PR DESCRIPTION
**Pull request by saghul**

### CODE REVIEW

**Comment by saghul** [comment]
As discussed, @ioc32

**Comment by ioc32** [comment]
Yo :)

Can't quite remember so let me ask... would setting the
dhcp.extra_resolvers to an empty list work for you?
If it does not, let's just merge your commit.

Also, if we're to merge it, maybe we can do without the jinja2 "do"
extension in ansible.cfg now?
I don't think we're using it anywhere else (out of the top of my head).

On Tue, Sep 15, 2015 at 9:53 AM, Saúl Ibarra Corretgé <
notifications@github.com> wrote:

> As discussed, @ioc32 https://github.com/ioc32
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ioc32/openhrc/pull/13#issuecomment-140312252.

## 

"If you want to go fast, go alone. If you want to go far, go together."

**Comment by saghul** [comment]
> Can't quite remember so let me ask... would setting the dhcp.extra_resolvers to an empty list work for you? If it does not, let's just merge your commit.

It doesn't. We use that list for unbound and recurse to them.

> Also, if we're to merge it, maybe we can do without the jinja2 "do" extension in ansible.cfg now? I don't think we're using it anywhere else (out of the top of my head).

Good call, I'll check that out.

**Comment by saghul** [comment]
Sorry, you're right! We don't use that anywhere.

**Comment by saghul** [comment]
Updated, PTAL.

**Pull request merged**
